### ISSUE TITLE
service "telegram-bot" refers to undefined volume vaaski-telegram-ytdl: invalid compose project

### ISSUE THREAD

**Issue by tqtrung99** [vaaski/telegram-ytdl#106]
Got this error when run "docker compose up -d" on Ubuntu 24.04, Docker version 27.3.1, build ce12230

```
services:
  telegram-bot:
    image: ghcr.io/vaaski/telegram-ytdl:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - vaaski-telegram-ytdl:/app/storage
    environment:
```

fix by

```
services:
  telegram-bot:
    image: ghcr.io/vaaski/telegram-ytdl:latest
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./vaaski-telegram-ytdl:/app/storage
    environment:
```
not sure if you can fix for all OS
